#!/usr/bin/env bash
set -euo pipefail

COMMON_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$(cd "${COMMON_DIR}/.." && pwd)"
PLATFORM_DIR="$(cd "${SCRIPTS_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${PLATFORM_DIR}/.." && pwd)"
BUILD_DIR="${PLATFORM_DIR}/.build"
ENV_FILE="${PLATFORM_DIR}/.env.generated"

DEMO_NAMESPACE="${DEMO_NAMESPACE:-demo}"
CATALOG_NAMESPACE="${CATALOG_NAMESPACE:-runtimeconditions-system}"
CATALOG_CONFIGMAP="${CATALOG_CONFIGMAP:-runtimeconditions-api-catalog}"
APP_NAME="${APP_NAME:-request-logger}"
APP_PORT="${APP_PORT:-8080}"
TODOS_API_NAME="${TODOS_API_NAME:-todos-api}"
TODOS_API_PORT="${TODOS_API_PORT:-8080}"

mkdir -p "${BUILD_DIR}"

log() {
  printf '[runtimeconditions] %s\n' "$*"
}

fail() {
  printf '[runtimeconditions] error: %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

require_kubectl_context() {
  require_cmd kubectl
  local context
  context="$(kubectl config current-context 2>/dev/null || true)"
  [[ -n "${context}" ]] || fail "kubectl has no current context"
  log "kubectl context: ${context}"
}

source_generated_env() {
  if [[ -f "${ENV_FILE}" ]]; then
    # shellcheck disable=SC1090
    source "${ENV_FILE}"
  fi
}

write_generated_env() {
  cat >"${ENV_FILE}" <<EOF
# Generated by a platform image reference script.
REDIS_PIPELINE_IMAGE=${REDIS_PIPELINE_IMAGE}
CILIUM_API_ACCESS_PIPELINE_IMAGE=${CILIUM_API_ACCESS_PIPELINE_IMAGE}
CILIUM_NAMESPACE_LOCKDOWN_PIPELINE_IMAGE=${CILIUM_NAMESPACE_LOCKDOWN_PIPELINE_IMAGE}
S3_BUCKET_PIPELINE_IMAGE=${S3_BUCKET_PIPELINE_IMAGE}
APPLICATION_RELEASE_PIPELINE_IMAGE=${APPLICATION_RELEASE_PIPELINE_IMAGE}
TODOS_API_IMAGE=${TODOS_API_IMAGE}
REQUEST_LOGGER_IMAGE=${REQUEST_LOGGER_IMAGE}
DEMO_NAMESPACE=${DEMO_NAMESPACE}
CATALOG_NAMESPACE=${CATALOG_NAMESPACE}
CATALOG_CONFIGMAP=${CATALOG_CONFIGMAP}
APP_NAME=${APP_NAME}
APP_PORT=${APP_PORT}
TODOS_API_NAME=${TODOS_API_NAME}
TODOS_API_PORT=${TODOS_API_PORT}
EOF
}

render_template() {
  local source_file="$1"
  local target_file="$2"
  shift 2

  cp "${source_file}" "${target_file}"
  while (($#)); do
    local key="$1"
    local value="$2"
    shift 2
    local escaped
    escaped="$(printf '%s' "${value}" | sed 's/[&|]/\\&/g')"
    sed -i.bak "s|__${key}__|${escaped}|g" "${target_file}"
    rm -f "${target_file}.bak"
  done
}

wait_for_deployment() {
  local namespace="$1"
  local name="$2"
  local timeout="${3:-180s}"
  kubectl -n "${namespace}" rollout status "deployment/${name}" --timeout="${timeout}"
}

wait_for_crd() {
  local name="$1"
  local timeout="${2:-120s}"
  local timeout_seconds deadline
  timeout_seconds="$(duration_to_seconds "${timeout}")"
  deadline="$(($(date +%s) + timeout_seconds))"

  until kubectl get "crd/${name}" >/dev/null 2>&1; do
    if (( $(date +%s) >= deadline )); then
      fail "timed out waiting for CRD ${name} to be created"
    fi
    sleep 2
  done

  kubectl wait --for=condition=Established "crd/${name}" --timeout="${timeout}"
}

duration_to_seconds() {
  local value="$1"
  if [[ "${value}" =~ ^([0-9]+)$ ]]; then
    printf '%s\n' "${BASH_REMATCH[1]}"
  elif [[ "${value}" =~ ^([0-9]+)s$ ]]; then
    printf '%s\n' "${BASH_REMATCH[1]}"
  elif [[ "${value}" =~ ^([0-9]+)m$ ]]; then
    printf '%s\n' "$((BASH_REMATCH[1] * 60))"
  else
    fail "unsupported timeout format: ${value}"
  fi
}
